// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76iULmMeUnIZNr0fAA0YgL-NF15OR2Uw',
    appId: '1:403656762919:web:826fc1c53405cffae09002',
    messagingSenderId: '403656762919',
    projectId: 'handymanfyp-51049',
    authDomain: 'handymanfyp-51049.firebaseapp.com',
    storageBucket: 'handymanfyp-51049.firebasestorage.app',
    measurementId: 'G-YTJGQD1F0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_GuUq_168k5ODI7Tdwq3Z0OFwHc1_bv4',
    appId: '1:403656762919:android:f53944d80cf37ce5e09002',
    messagingSenderId: '403656762919',
    projectId: 'handymanfyp-51049',
    storageBucket: 'handymanfyp-51049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-bJLdqKpALcRHunzYQ3d7-E-UCz8yAzs',
    appId: '1:403656762919:ios:58aa3badeb8ad18ae09002',
    messagingSenderId: '403656762919',
    projectId: 'handymanfyp-51049',
    storageBucket: 'handymanfyp-51049.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-bJLdqKpALcRHunzYQ3d7-E-UCz8yAzs',
    appId: '1:403656762919:ios:58aa3badeb8ad18ae09002',
    messagingSenderId: '403656762919',
    projectId: 'handymanfyp-51049',
    storageBucket: 'handymanfyp-51049.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB76iULmMeUnIZNr0fAA0YgL-NF15OR2Uw',
    appId: '1:403656762919:web:873b1a7b81772cabe09002',
    messagingSenderId: '403656762919',
    projectId: 'handymanfyp-51049',
    authDomain: 'handymanfyp-51049.firebaseapp.com',
    storageBucket: 'handymanfyp-51049.firebasestorage.app',
    measurementId: 'G-YQY6H8CHHZ',
  );
}
